<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>MclLauncher</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <EnableMsixTooling>true</EnableMsixTooling>
    <UseRidGraph>true</UseRidGraph>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250205002" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="injector.exe;Mcl.Core.dll;MinecraftProxy.dll;es.exe;Everything.exe" />
    <EmbeddedResource Include="injector.exe" LogicalName="MclLauncher.Resources.injector.exe" />
    <EmbeddedResource Include="Mcl.Core.dll" LogicalName="MclLauncher.Resources.Mcl.Core.dll" />
    <EmbeddedResource Include="MinecraftProxy.dll" LogicalName="MclLauncher.Resources.MinecraftProxy.dll" />
    <EmbeddedResource Include="es.exe" LogicalName="MclLauncher.Resources.es.exe" Condition="Exists('es.exe')" />
    <EmbeddedResource Include="4399_demo.txt" LogicalName="MclLauncher.Resources.4399_demo.txt" />
    <Content Include="4399_demo.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="dist/**;dist-*/**" />
    <None Remove="dist/**;dist-*/**" />
    <EmbeddedResource Remove="dist/**;dist-*/**" />
  </ItemGroup>
</Project>





